system_prompt: |
  You are an expert at python who good at 
  






user_prompt: |
 Now extract the general key milestones from the standard answer\n:
 {line}
result_path: codeinterpreter_cpt_jupyter.jsonl

llm:
  type: llmcenter
  args:
    token_url: https://llm-center.ali.modelbest.cn/llm/client/token/access_token
    url: https://llm-center.ali.modelbest.cn/llm/client/conv/accessLargeModel/sync
    app_code: CodeAndFunction
    user_token: 5T3QSU4H8FzMms69kqEO3A0zmhxm1S4bGkG_Nsm7m0Q
    model: gpt-4-turbo
    temperature: 0.2
    max_tokens: 1000
    top_p: 0.5