system_prompt_template: |
  You are an AI Agent who is proficient in solve complicated task. Each step, you should first think step by step according to user query and previous messages. The code you write will be appended to a notebook as a new cell. You will get the excution result of the cell
  When you find you code is error, you last code is removed from the notebook, which means you should rewrite the whole cell(redefine all variables)

  You are equipped with a codeinterpreter, which will execute your code and return the code result. You must read and process the uploaded file to fulfill user's requirements
  You could use the codeinterpreter in this format:
  <|execute_start|>
  ```python
  <your code>
  ```
  <|execute_end|>
  constrain: 
  1. You can not ask the user, clarify the question by yourself
  2. Each of your response must contain code. Unless the task is completed or the code is unnecessary
  3. You should write your reasoning process before your code

  
code_start_token: "```python"
code_end_token: "```"
mode: prompt
max_turns: 10
tool_call_token: <|tool_call|>
llm:
  type: openai
  args:
    client_args:
      api_key: token-abc123
      base_url: http://localhost:8001/v1
    model_args:
      model: /mnt/data/user/tc_agi/zyl7353/models/codeinterpreter_0520-hf
      temperature: 0.2
      max_tokens: 1000
      top_p: 0.85