system_prompt_template: |
  你可以编写python代码并执行来帮助解决用户问题，如果用户的问题可以通过python代码解决，请将python代码放在<|execute_start|>和<|execute_end|>中间。
code_start_token: "<|execute_start|>"
code_end_token: "<|execute_end|>"
mode: prompt
max_turns: 10
tool_call_token: <|tool_call|>
llm:
  type: openai
  args:
    client_args:
      api_key: token-abc123
      base_url: http://localhost:8000
    model_args:
      model: /mnt/data/user/tc_agi/panyinxu/models/Qwen1.5-32B-Chat
      temperature: 0.2
      max_tokens: 1000
      top_p: 0.5